/**********************************************************************************************************************
 * \file DsAdc.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "DsAdc.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
uint8 dsadcChannelAvailable[IFXDSADC_NUM_CHANNELS] = { 1, 1, 1, 1, 1, 1 };
IfxDsadc_Dsadc_Channel DsAdcChannels[IFXDSADC_NUM_CHANNELS];
sint16 DsAdcResult[IFXDSADC_NUM_CHANNELS];
float32 DsAdcResultVoltage [IFXDSADC_NUM_CHANNELS];
float32 DsAdcSupplyVoltage = 3.3;
float32 DsAdcmaxValue = 21613.0;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void DsAdc_Init(IfxDsadc_Dsadc *DsAdc, IfxDsadc_ChannelId* DsAdcChannelsId, uint8 channelsNum)
{
  if (channelsNum > 6)
  {
    channelsNum = 6;
  }
  else
  {

  }
  IfxDsadc_Dsadc_Config dsadcConfig;

  IfxDsadc_Dsadc_initModuleConfig(&dsadcConfig, &MODULE_DSADC);
  IfxDsadc_Dsadc_initModule(DsAdc, &dsadcConfig);

  // create channel config
  IfxDsadc_Dsadc_ChannelConfig dsadcChannelConfig;
  IfxDsadc_Dsadc_initChannelConfig(&dsadcChannelConfig, DsAdc);

  /* Modify default configuration of the channel */
  dsadcChannelConfig.combFilter.decimationFactor  = 32;
  dsadcChannelConfig.combFilter.startValue = 32;
  dsadcChannelConfig.combFilter.combFilterShift = IfxDsadc_MainCombFilterShift_shiftBy3,
  dsadcChannelConfig.firFilter.fir0Enabled = TRUE;
  dsadcChannelConfig.firFilter.fir1Enabled = TRUE;
  dsadcChannelConfig.firFilter.dataShift = IfxDsadc_FirDataShift_shiftBy1;

  // initialize channels
  for(int chn = 0; chn < channelsNum; ++chn) {
      if( dsadcChannelAvailable[chn] )
      {
          dsadcChannelConfig.channelId = DsAdcChannelsId[chn];

          IfxDsadc_Dsadc_initChannel(&DsAdcChannels[chn], &dsadcChannelConfig);
      }
  }
  IfxDsadc_Dsadc_startScan(DsAdc, 0x3f, 0x3f);

}

void DsAdc_Read(IfxDsadc_Dsadc *DsAdc, uint8 channelsNum)
{
  for(int chn = 0; chn < channelsNum; ++chn)
  {
      if( dsadcChannelAvailable[chn] )
      {
        DsAdcResult[chn] = IfxDsadc_Dsadc_getMainResult(&DsAdcChannels[chn]);
        DsAdcResultVoltage[chn] = ((float32)DsAdcResult[chn] * DsAdcSupplyVoltage)/ DsAdcmaxValue;
      }
  }
}
