/**********************************************************************************************************************
 * \file HySrf05.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "HySrf05.h"
#include "INTERRUPTS.h"
#include "pinsReadWrite.h"
#include "Bsp.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Echo is the 00.11
 * Trigger is the 00.7
 */
#define ECHO_PIN &MODULE_P00,11
#define TRIGGER_PIN &MODULE_P00,7
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
Ifx_TickTime HySrfDelay;
float HySrf05Distance = 0;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/


void HySrf05_init(void)
{
  HySrfDelay = IfxStm_getTicksFromMicroseconds(BSP_DEFAULT_TIMER, 10);
  setPinInputNoPull(ECHO_PIN);
  setPinOutput(TRIGGER_PIN);
  IfxPort_setPinPadDriver(TRIGGER_PIN, IfxPort_PadDriver_ttlSpeed1);
}

void HySrf05_captureDistance(void)
{
  static uint64 echoTicks = 0;
  static float echo = 0;
  setPinOutputTrue(TRIGGER_PIN);
  wait(HySrfDelay);
  setPinOutputFalse(TRIGGER_PIN);
  while (getPinState(ECHO_PIN) == FALSE){}
  echoTicks = IfxStm_get(&MODULE_STM0);
  while (getPinState(ECHO_PIN) == TRUE) {}
  echoTicks = IfxStm_get(&MODULE_STM0) - echoTicks;
  echo = (float)(echoTicks)/IfxStm_getFrequency(&MODULE_STM0);

  /* Distance = 100*period*speed_of_light/2  cm */
  HySrf05Distance = (100*(float)echo*343)/2;
}
