/**********************************************************************************************************************
 * \file I2C.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "MPU6050.h"
#include "Ifx_Types.h"
#include "IfxI2c_I2c.h"
#include "Bsp.h"
#include <stdint.h>
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define waitTime 200
#define Baudrate 400000

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
volatile uint8 i2cRxTxBuffer[6];
static const uint8 I2cAddress = 0x68;
IfxI2c_I2c myi2c;
IfxI2c_I2c_Device myi2cdev;
volatile int16_t accelValues[3];
float accelX_g,accelY_g,accelZ_g;
float gyroX_g, gyroY_g, gyroZ_g;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void mpu6050_write(uint8 *data,Ifx_SizeT size);
void mpu6050_read(uint8* registerAddress, Ifx_SizeT size);
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
//i2c init function
void mpu6050_init()
{
    IfxI2c_I2c_Config config;
    IfxI2c_I2c_initConfig(&config, &MODULE_I2C0);
    const IfxI2c_Pins pins = {
            &IfxI2c0_SCL_P13_1_INOUT,
            &IfxI2c0_SDA_P13_2_INOUT,
            IfxPort_PadDriver_ttlSpeed1
    };
    config.pins = &pins;

    config.baudrate = Baudrate;

    IfxI2c_I2c_initModule(&myi2c,&config);

    //device config section
    IfxI2c_I2c_deviceConfig i2cDeviceConfig;
    IfxI2c_I2c_initDeviceConfig(&i2cDeviceConfig, &myi2c);
    i2cDeviceConfig.deviceAddress = I2cAddress<<1;
    IfxI2c_I2c_initDevice(&myi2cdev, &i2cDeviceConfig);
}

//i2c write simple function
void mpu6050_write(uint8 *data,Ifx_SizeT size)
{
    while(IfxI2c_I2c_write(&myi2cdev,&data[0],size)==IfxI2c_I2c_Status_nak);
}

//i2c read simple function
void mpu6050_read(uint8* registerAddress, Ifx_SizeT size)
{

    uint8 registerArray[1] = {*registerAddress};
    // Send the register address to the device
    while (IfxI2c_I2c_write(&myi2cdev, &registerArray[0], 0) == IfxI2c_I2c_Status_nak);

    // Read the data from the device
    while (IfxI2c_I2c_read(&myi2cdev, i2cRxTxBuffer, size) == IfxI2c_I2c_Status_nak);
}

void initialize_mpu6050_values(){
    uint8 data[2];
    uint8 who_am_i = 0x75;
    Ifx_TickTime Delay200ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, waitTime);
    mpu6050_read(&who_am_i,1);
        data[0] = 0x6B;
        data[1] = 0x00;
        mpu6050_write(data,2);
        wait(Delay200ms);

        data[0] = 0x1C;
        data[1] = 0x00;
        mpu6050_write(data,2);
        wait(Delay200ms);
}

void readData_mpu6050(){

    uint8 ACCEL_XOUT_H = 0x3B;
    uint8 GYRO_XOUT_H = 0x43;
    //uint8 ACCEL_XOUT_L = 0x3C;
    //uint8 ACCEL_YOUT_H = 0x3D;
    //uint8 ACCEL_YOUT_L = 0x3E;
   //uint8 ACCEL_ZOUT_H = 0x3F;
    //uint8 ACCEL_ZOUT_L = 0x40;//

    mpu6050_read(&ACCEL_XOUT_H, 6);
    int16_t accelX, accelY, accelZ;
    accelX = (int16_t)(i2cRxTxBuffer[0]<< 8 | i2cRxTxBuffer[1]);
    accelY = (int16_t)(i2cRxTxBuffer[2]< 8 | i2cRxTxBuffer[3]);
    accelZ = (int16_t)(i2cRxTxBuffer[4]<< 8 | i2cRxTxBuffer[5]);

    accelX_g = accelX / 16384.0;
    accelY_g = accelY / 16384.0;
    accelZ_g = accelZ / 16384.0;

    mpu6050_write(&GYRO_XOUT_H,6);

    int16_t gyrolX, gyrolY, gyrolZ;
    gyrolX = (int16_t)(i2cRxTxBuffer[0]<< 8 | i2cRxTxBuffer[1]);
    gyrolY = (int16_t)(i2cRxTxBuffer[2]< 8 | i2cRxTxBuffer[3]);
    gyrolZ = (int16_t)(i2cRxTxBuffer[4]<< 8 | i2cRxTxBuffer[5]);

    gyroX_g = accelX / 131.0;
    gyroY_g = accelY / 131.0;
    gyroZ_g = accelZ / 131.0;


    //accelValues[0] = (int16_t)((i2cRxTxBuffer[0] << 8) | i2cRxTxBuffer[1]);
    //accelValues[1] = (int16_t)((i2cRxTxBuffer[2] << 8) | i2cRxTxBuffer[3]);
    //accelValues[2] = (int16_t)((i2cRxTxBuffer[4] << 8) | i2cRxTxBuffer[5]);


}

