/**********************************************************************************************************************
 * \file Tim.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Tim.h"
#include "PWM_GENERATOR.h"
#include "INTERRUPTS.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
float TimPeriod = 0.0;
sint32 TimDutyCycle = 0.0;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void Tim_Init(IfxGtm_Tim_In* TimDriver, Tim_Pin* pin)
{
  if (GtmModuleInit == FALSE)
  {
    IfxGtm_enable(&MODULE_GTM);                                         /* Enable the GTM                           */

    GtmModuleInit = TRUE;
  }
  if (CmuClkEn == FALSE)
  {
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK0);        /* Enable the CMU clock 0                   */
    CmuClkEn = TRUE;
  }
  IfxGtm_Tim_In_Config configTIM;

  IfxGtm_Tim_In_initConfig(&configTIM, &MODULE_GTM);                  /* Initialize default parameters            */
  configTIM.filter.irqOnGlitch = FALSE;
  configTIM.timIndex = pin->tim;
  configTIM.channelIndex = pin->channel;
  configTIM.filter.inputPin = pin;                                /* Select input port pin                    */
  configTIM.filter.inputPinMode = IfxPort_InputMode_noPullDevice;         /* Select input port pin mode               */
  IfxGtm_Tim_In_init(TimDriver, &configTIM);                       /* Initialize the TIM                       */

}

float Tim_GetPeriod(IfxGtm_Tim_In* TimDriver)
{
  IfxGtm_Tim_In_update(TimDriver);                                    /* Update the measured data         */
  TimPeriod = IfxGtm_Tim_In_getPeriodSecond(TimDriver);
  return TimPeriod;
}

sint32 Tim_GetDuty(IfxGtm_Tim_In* TimDriver)
{
  IfxGtm_Tim_In_update(TimDriver);                                    /* Update the measured data         */
  TimDutyCycle = IfxGtm_Tim_In_getPulseLengthTick(TimDriver);
  return TimDutyCycle;
}
