/**********************************************************************************************************************
 * \file std_int.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "std_int.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void memcpy(void* src, void* dst, uint16 size)
{
  uint32 src_addr = (uint32)src;
  uint32 dst_addr = (uint32)dst;
  uint16 count;
  uint16 mod = size % 4;
  if ( ( (src_addr % 4)==0) &&  ((dst_addr % 4) == 0))
  {
    uint32 *src32 = (uint32*)src;
    uint32 *dst32 = (uint32*)dst;
    count = size;
    while(count--)
    {
      *dst32++ = *src32++;
    }
  }
  else if ( ( (src_addr % 4)==2) && ( (dst_addr % 4)==2) && (mod == 2) )
  {
    if (mod == 0)
    {
      uint32 *src32 = (uint32*)src;
      uint32 *dst32 = (uint32*)dst;
      count = size >> 1;
      while(count--)
      {
        *dst32++ = *src32++;
      }
    }
    else
    {
      uint16 *src16 = (uint16*)src;
      uint16 *dst16 = (uint16*)dst;
      uint16 count = size;
      while(count--)
      {
        *dst16++ = *src16++;
      }
    }
  }

  else
  {
    if (mod == 0)
    {
      uint32 *src32 = (uint32*)src;
      uint32 *dst32 = (uint32*)dst;
      count = size >> 2;
      while(count--)
      {
        *dst32++ = *src32++;
      }
    }
    else if (mod == 2)
    {
      uint16 *src16 = (uint16*)src;
      uint16 *dst16 = (uint16*)dst;
      uint16 count = size >> 1;
      while(count--)
      {
        *dst16++ = *src16++;
      }
    }
    else
    {
      uint8 *src8 = (uint8*)src;
      uint8 *dst8 = (uint8*)dst;
      uint16 count = size;
      while(count--)
      {
        *dst8++ = *src8++;
      }
    }
  }
}


void memset_var(void* dst, void* val , uint16 size)
{
  uint32 src_addr = (uint32)dst;
  uint32 dst_addr = (uint32)val;
  uint16 count;
  uint16 mod = size % 4;
  if ((src_addr % 4)!=(dst_addr % 4))
  {
    return;
  }

  if ( ( (src_addr % 4)==0) &&  ((dst_addr % 4) == 0))
  {
    uint32 *dst32 = (uint32*)dst;
    uint32 val32 = *(uint32*)val;
    count = size;
    while(count--)
    {
      *dst32++ = val32;
    }
  }
  else if ( ( (src_addr % 4)==2) && ( (dst_addr % 4)==2) )
  {
    if (mod == 0)
    {
      uint32 *dst32 = (uint32*)dst;
      uint16 val16 = *(uint16*)val;
      uint32 val32 = ((uint32)val16 << 16) | (uint32)val16;
      count = size >> 1;
      while(count--)
      {
        *dst32++ = val32;
      }
    }
    else
    {
      uint16 *dst16 = (uint16*)dst;
      uint16 val16 = *(uint16*)val;
      uint16 count = size;
      while(count--)
      {
        *dst16++ = val16;
      }
    }
  }

  else
  {
    if (mod == 0)
    {
      uint32 *dst32 = (uint32*)dst;
      uint8 val8 = *(uint8*)val;
      uint32 val32 = ((uint32)val8 << 24) | ((uint32)val8 << 16) | ((uint32)val8 << 8) | (uint32)val8;
      count = size >> 2;
      while(count--)
      {
        *dst32++ = val32++;
      }
    }
    else if (mod == 2)
    {
      uint16 *dst16 = (uint16*)dst;
      uint8 val8 = *(uint8*)val;
      uint16 val16 = ((uint16)val8 << 8) | (uint16)val8;
      uint16 count = size >> 1;
      while(count--)
      {
        *dst16++ = val16;
      }
    }
    else
    {
      uint8 *dst8 = (uint8*)dst;
      uint8 val8 = *(uint8*)val;
      uint16 count = size;
      while(count--)
      {
        *dst8++ = val8;
      }
    }
  }
}
