
/**********************************************************************************************************************
 * \file phaseShiftPwm.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "../InfineonArduinoLike/AtomAndAru/AtomPhaseSerial.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define MAX_ATOM_CHANNELS           3
#define MASTER_TIMER_ISR            3
#define ATOM_BITSHIFT               15



/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* Structure for three phase PWM output configuration and handling */
typedef struct
{
    IfxGtm_Atom_Timer    timer;                  /* Timer driver                                                      */
    IfxGtm_Atom_PwmHl    pwm;                    /* GTM TOM PWM driver object                                         */
    Ifx_TimerValue      pwmOnTimes[3];          /* PWM ON-time for 3 phases                                          */
    IfxGtm_Atom_Serial  update;
    IfxGtm_Atom_Timer   SpiClk;
    uint32              spiPeriod;
} Serial_Timers_Output;


static Serial_Timers_Output AtomPhaseSerial_Output;

volatile ATOMPHASESERIAL_STATE AtomPhaseSerial_State = ATOM_SPI_WAIT;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
IFX_INTERRUPT(AtomPhaseSerial_Isr,0, MASTER_TIMER_ISR);
void AtomPhaseSerial_Isr(void)
{
  switch (AtomPhaseSerial_State)
  {
    case ATOM_SPI_WAIT:
    {
      /* Do nothing */
      break;
    }

    case ATOM_SPI_START:
    {
      IfxGtm_Atom_Timer_run(&AtomPhaseSerial_Output.SpiClk);
      IfxGtm_Atom_Timer_disableUpdate(&AtomPhaseSerial_Output.SpiClk); /* Disable the update of Spi Timer */
      IfxGtm_Atom_Ch_setCompareShadow(AtomPhaseSerial_Output.SpiClk.atom, AtomPhaseSerial_Output.SpiClk.triggerChannel, (3*AtomPhaseSerial_Output.spiPeriod) >> 2,  AtomPhaseSerial_Output.spiPeriod >> 2);
      IfxGtm_Atom_Timer_applyUpdate(&AtomPhaseSerial_Output.SpiClk);  /* Start every PWM signal at the same time */
      AtomPhaseSerial_State =  ATOM_SPI_RUN;
      break;
    }

    case ATOM_SPI_END:
    {
      /* Do nothing */
      IfxGtm_Atom_Timer_stop(&AtomPhaseSerial_Output.SpiClk);
      AtomPhaseSerial_State = ATOM_SPI_WAIT;
      break;
    }

    default:
    {
      break;
    }
  }
}

IFX_STATIC void IfxGtmTomSerialSetSpiClk(IfxGtm_Atom_ToutMap* SpiPin, IfxGtm_Cmu_Clk Clock, uint32 frequency)
{
  IfxGtm_Atom_Timer_Config atomConfig;

  atomConfig.base.frequency                  = (float32)frequency;
  atomConfig.base.isrPriority                = 0;
  atomConfig.base.isrProvider                = IfxSrc_Tos_cpu0;
  atomConfig.base.minResolution              = 0;
  atomConfig.base.trigger.outputMode         = IfxPort_OutputMode_pushPull;
  atomConfig.base.trigger.outputDriver       = IfxPort_PadDriver_cmosAutomotiveSpeed1;
  atomConfig.base.trigger.risingEdgeAtPeriod = FALSE;
  atomConfig.base.trigger.outputEnabled      = TRUE;
  atomConfig.base.trigger.enabled            = TRUE;
  atomConfig.base.trigger.triggerPoint       = 0;
  atomConfig.base.trigger.isrPriority        = 0;
  atomConfig.base.trigger.isrProvider        = IfxSrc_Tos_cpu0;
  atomConfig.base.countDir                   = IfxStdIf_Timer_CountDir_up;
  atomConfig.base.startOffset                = 0.0;
  atomConfig.gtm            = &MODULE_GTM;
  atomConfig.atom           = SpiPin->atom;
  atomConfig.timerChannel   = SpiPin->channel-1;
  atomConfig.triggerOut     = SpiPin;
  atomConfig.clock          = Clock;
  atomConfig.base.countDir  = IfxStdIf_Timer_CountDir_up;
  atomConfig.irqModeTimer   = IfxGtm_IrqMode_level;
  atomConfig.irqModeTrigger = IfxGtm_IrqMode_pulseNotify;
  atomConfig.initPins       = TRUE;

  IfxGtm_Atom_Timer_init(&AtomPhaseSerial_Output.SpiClk, &atomConfig);
}


/*This function sets default pwm signals for every phase*/
IFX_STATIC void IfxGtmTomSerialUpdateOff(IfxGtm_Atom_PwmHl *driver, Ifx_TimerValue *tOn)
{
  IFX_UNUSED_PARAMETER(tOn)
  uint8 ChannelIndex;

  for (ChannelIndex = 0; ChannelIndex < driver->base.channelCount; ChannelIndex++)
  {
    IfxGtm_Atom_Ch_setCompareOneShadow(driver->atom, driver->ccxTemp[ChannelIndex],
          0);
  }
}


IFX_STATIC void IfxGtmTomSerialUpdatePeriod(IfxGtm_Atom_PwmHl *driver)
{
  uint8 ChannelIndex;
  for (ChannelIndex = 0; ChannelIndex < driver->base.channelCount; ChannelIndex++)
  {
    IfxGtm_Atom_Ch_setCompareZeroShadow(driver->atom, driver->ccxTemp[ChannelIndex],
        ATOM_BITSHIFT);
  }
}

/*This function runs the function pointer of the AtomPhaseSerial_Output.update structure and sets the dutycycle of the pwm signals*/
void IfxGtm_AtomSerialThreeTimersSetOnTime(IfxGtm_Atom_PwmHl *driver, Ifx_TimerValue *tOn)
{
    AtomPhaseSerial_Output.update.setMode(driver, tOn);
}


/*This function Starts the three phase pwm signals*/
IFX_STATIC void IfxGtmTomSerialUpdate(IfxGtm_Atom_PwmHl *driver, Ifx_TimerValue *tOn)
{
  uint8          channelIndex;
  Ifx_TimerValue period;

  period = driver->timer->base.period;

  for (channelIndex = 0; channelIndex < driver->base.channelCount; channelIndex++)
  {
    IfxGtm_Atom_Ch_setCompareOneShadow(driver->atom, driver->ccxTemp[channelIndex],
        tOn[channelIndex]);
  }
}

/*This pointer of structures has the different modes of the three phase signals, at first we use the configuration of
 * IfxGtmTomSerialchModes[1] structure and then the configuration of IfxGtmTomSerialchModes[0] structure*/
IFX_STATIC IFX_CONST IfxGtm_Atom_Serial IfxGtmTomSerialchModes[2] = {
    {Ifx_Pwm_Mode_centerAligned,         FALSE, &IfxGtmTomSerialUpdate  },
    {Ifx_Pwm_Mode_off,                   FALSE, &IfxGtmTomSerialUpdateOff   }
    /*To add two more modes*/
};


/*This function sets the mode of the three phase pwm signals*/
boolean IfxGtm_AtomSerialThreeTimersSetMode(IfxGtm_Atom_PwmHl *driver, Ifx_Pwm_Mode mode)
{
    boolean                Result = TRUE;
    IfxGtm_Atom_PwmHl_Base *Base   = &driver->base;

    if (Base->mode != mode)
    {
        if (mode > Ifx_Pwm_Mode_off)
        {
            mode = Ifx_Pwm_Mode_off;
            Result = FALSE;
        }

        IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, mode == IfxGtm_Atom_Pwmccx_modes[mode].mode);

        Base->mode             = mode;
        AtomPhaseSerial_Output.update         = IfxGtmTomSerialchModes[0];

            driver->ccxTemp   = driver->ccx;

        {   /* Workaround to enable the signal inversion required for center aligned inverted
             * and right aligned modes */
            /** \note that changing signal level may produce short circuit at the power stage,
             * in which case the inverter must be disable during this action. */

            /* Ifx_Pwm_Mode_centerAligned and Ifx_Pwm_Mode_LeftAligned use inverted=FALSE */
            /* Ifx_Pwm_Mode_centerAlignedInverted and Ifx_Pwm_Mode_RightAligned use inverted=TRUE */
            uint32 ChannelIndex;

            for (ChannelIndex = 0; ChannelIndex < driver->base.channelCount; ChannelIndex++)
            {
                IfxGtm_Atom_Ch Channel;

                Channel = driver->ccx[ChannelIndex];
                IfxGtm_Atom_Ch_setSignalLevel(driver->atom, Channel, Base->ccxActiveState); /*Every phase must have the same signal level, active state high*/

            }
        }
    }

    return Result;
}



/*This function returns true when the three timers are initialized correctly*/
boolean IfxGtm_AtomSerialChannelsInit(IfxGtm_Atom_PwmHl *driver, IfxGtm_Atom_PwmHl_Config *config) {
    boolean           Result = TRUE;
    uint16            ChannelMask;
    uint16            ChannelsMask = 0;
    uint32            ChannelIndex;
    IfxGtm_Atom_Timer  *Timer        = config->timer;

    driver->base.mode             = Ifx_Pwm_Mode_init;
    driver->timer                 = Timer;
    driver->base.setMode          = 0;
    driver->base.inverted         = FALSE;
    driver->base.ccxActiveState   = config->base.ccxActiveState; /*Gets the active state of pwm signals from the configuration struct*/
    driver->base.channelCount     = config->base.channelCount; /*Gets the max channel count of controlled pwm signals by the master timer*/


    driver->atom = &(Timer->gtm->ATOM[config->atom]); /*Gets the Tom used as master*/

    /* config->ccx[0] is used for the definition of the TGC */
    driver->agc = (Ifx_GTM_ATOM_AGC *)&driver->atom->AGC.GLB_CTRL; /*In case we have channels from 0-6 we enable global control register 0*/


    IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, config->base.channelCount <= IfxGtm_Atom_PWMHL_MAX_NUM_CHANNELS); /*In case we have less than 2 controlled pwm signals return 0*/

    IfxGtm_Cmu_Clk Clock = IfxGtm_Atom_Ch_getClockSource(Timer->atom, Timer->timerChannel); /*Set prescaler for every phase*/

    for (ChannelIndex = 0; ChannelIndex < config->base.channelCount; ChannelIndex++)
    {
        IfxGtm_Atom_Ch Channel;
        /* CCX */
        Channel                   = config->ccx[ChannelIndex]->channel;
        driver->ccx[ChannelIndex] = Channel;
        ChannelMask               = 1 << (Channel);
        ChannelsMask             |= ChannelMask;

        /* Initialize the timer part */
        IfxGtm_Atom_Ch_configureOutputSerial(driver->atom, Channel, Clock,
            driver->base.ccxActiveState, FALSE);

        /* Initialize the port */
        if (config->initPins == TRUE)
        {
            IfxGtm_PinMap_setAtomTout(config->ccx[ChannelIndex],
                config->base.outputMode, config->base.outputDriver);
        }

    }
    IfxGtm_Atom_Agc_enableChannelsOutput(driver->agc, ChannelsMask, 0, TRUE);
    IfxGtm_Atom_Agc_enableChannels(driver->agc, ChannelsMask, 0, TRUE);


    IfxGtm_AtomSerialThreeTimersSetMode(driver, Ifx_Pwm_Mode_off); /*Enable the timers by having zero dutycycle*/

    Ifx_TimerValue tOn[MAX_ATOM_CHANNELS] = {0};
    IfxGtmTomSerialUpdateOff(driver, tOn);     /* tOn do not need defined values */
    /* Transfer the shadow registers */
    IfxGtm_Atom_Agc_setChannelsForceUpdate(driver->agc, ChannelsMask, 0, 0, 0);
    IfxGtm_Atom_Agc_trigger(driver->agc);
    IfxGtm_Atom_Agc_setChannelsForceUpdate(driver->agc, 0, ChannelsMask, 0, 0);

    /* Enable timer to update the channels */
    for (ChannelIndex = 0; ChannelIndex < driver->base.channelCount; ChannelIndex++)
    {
        IfxGtm_Atom_Timer_addToChannelMask(Timer, driver->ccx[ChannelIndex]);
    }

    return Result;
}

/*Main function of the Three timers Phase shift PWM*/
void AtomPhaseSerial_Init(float32 baseFrequency,IfxGtm_Atom_ToutMap* masterPin, IfxGtm_Atom_ToutMapP* slavePins)
{
  IfxGtm_Cmu_Clk ClckSrc= IfxGtm_Cmu_Clk_5;
  IfxGtm_Cmu_Clk SpiClk = IfxGtm_Cmu_Clk_4;
  float32 frequency;
  /* Enable GTM, it is necessary if the GTM is not initialized earlier */
  IfxGtm_enable(&MODULE_GTM);

  frequency = IfxGtm_Cmu_getModuleFrequency(&MODULE_GTM);
  IfxGtm_Cmu_setClkFrequency(&MODULE_GTM, SpiClk, frequency);

  /* Set the global clock frequency to the max */
  IfxGtm_Cmu_setGclkFrequency(&MODULE_GTM, frequency);
  /* Set the CMU CLK0 */
  IfxGtm_Cmu_setClkFrequency(&MODULE_GTM, ClckSrc, baseFrequency);
  /* Enable the FXU clock and the SpiClock cmu clock */
  IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK5 | IFXGTM_CMU_CLKEN_CLK4);
  IfxGtm_Atom_Timer_Config TimerConfig;                                        /* Timer configuration              */
  IfxGtm_Atom_Timer_initConfig(&TimerConfig, &MODULE_GTM);                     /* Initialize timer configuration   */


  /*init pwm using the IfxGtm_Atom_Timer_Config of the Tom timer library*/
  TimerConfig.irqModeTrigger       = IfxGtm_IrqMode_level;              /* Enable the pulse of the Output signal as interrupt*/
  TimerConfig.base.frequency       = baseFrequency;                           /* Set timer frequency */
  TimerConfig.base.isrPriority     = MASTER_TIMER_ISR;                        /* Enable the master timer ISR */
  TimerConfig.base.isrProvider     = IfxSrc_Tos_cpu0;                         /* Isr on cpu 0 */
  TimerConfig.atom                  = masterPin->atom;                          /* Define the timer used */
  TimerConfig.timerChannel         = masterPin->channel;                      /* Define the channel used */
  TimerConfig.clock                = ClckSrc;

  IfxGtm_Atom_TimerSerial_init(&AtomPhaseSerial_Output.timer, &TimerConfig, ATOM_BITSHIFT , FALSE);   /* Initialize the TOM */
  IfxGtm_Atom_Agc_enableChannelUpdate(AtomPhaseSerial_Output.timer.agc,AtomPhaseSerial_Output.timer.triggerChannel,TRUE);

  /* Initialize the SpiClk Pwm */
  IfxGtmTomSerialSetSpiClk(slavePins[3], SpiClk, baseFrequency);
  /* Get the Spi Period */
  AtomPhaseSerial_Output.spiPeriod = IfxGtm_Atom_Ch_getCompareZero(AtomPhaseSerial_Output.SpiClk.atom, AtomPhaseSerial_Output.SpiClk.triggerChannel);
  /* Here we stop the spi clock and we will update it inside the isr */
  IfxGtm_Atom_Timer_stop(&AtomPhaseSerial_Output.SpiClk);

  /* Initialize the slave mosi channels */
  IfxGtm_Atom_PwmHl_Config PwmHlConfig;

  IfxGtm_Atom_ToutMapP Ccx[] =
          {
              slavePins[0], /* PWM High-side 1 */
              slavePins[1], /* PWM High-side 2 */
              slavePins[2]  /* PWM High-side 3 is null since the third pwm phase is provide by the master timer*/
          };
  IfxGtm_Atom_PwmHl_initConfig(&PwmHlConfig);
  PwmHlConfig.base.channelCount = MAX_ATOM_CHANNELS; /* Controlled channels are three */

  PwmHlConfig.base.outputMode = IfxPort_OutputMode_pushPull; /* Output mode is push pull */


  PwmHlConfig.base.outputDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1; /* Pad driver speed grade 1 */

  /* Set top PWM active state */
  PwmHlConfig.base.ccxActiveState = Ifx_ActiveState_low;


  PwmHlConfig.ccx   = Ccx;                        /* Assign the channels for High-side switches   */

  PwmHlConfig.timer = &AtomPhaseSerial_Output.timer;  /* Use as master timer the timer we initialized */
  PwmHlConfig.atom   = TimerConfig.atom;

  IfxGtm_AtomSerialChannelsInit(&AtomPhaseSerial_Output.pwm, &PwmHlConfig); /* Run the initialize of the three timers function */

  IfxGtm_AtomSerialThreeTimersSetMode(&AtomPhaseSerial_Output.pwm, Ifx_Pwm_Mode_centerAligned); /* Start the actual PWM signals */
  /* Update the input frequency */
  IfxGtm_Atom_Timer_updateInputFrequency(&AtomPhaseSerial_Output.timer);
  IfxGtm_Atom_Timer_run(&AtomPhaseSerial_Output.timer); /* Start the count of master timer */
  /* Calculate initial values of PWM duty cycles */
  AtomPhaseSerial_Output.pwmOnTimes[0] = 0; /* First controlled signal is shifted to a percentage of master timer's period */
  AtomPhaseSerial_Output.pwmOnTimes[1] = 0; /* Second controlled signal is shifted to two times the percentage of master timer's period */
  AtomPhaseSerial_Output.pwmOnTimes[2] = 0;
  /* Update PWM duty cycles */
  IfxGtm_Atom_Timer_disableUpdate(&AtomPhaseSerial_Output.timer); /* Disable the update of master timer */
  IfxGtmTomSerialUpdatePeriod(&AtomPhaseSerial_Output.pwm);
  IfxGtm_AtomSerialThreeTimersSetOnTime(&AtomPhaseSerial_Output.pwm, AtomPhaseSerial_Output.pwmOnTimes); /* Set the shadow registers of the controlled pwm signals */
  IfxGtm_Atom_Timer_applyUpdate(&AtomPhaseSerial_Output.timer);  /* Start every PWM signal at the same time */
}


void AtomPhaseSerial_SetDutyCycle(uint32* pwmOnTime)
{
  AtomPhaseSerial_Output.pwmOnTimes[0] = pwmOnTime[0]; /* First controlled signal is shifted to a percentage of master timer's period */
  AtomPhaseSerial_Output.pwmOnTimes[1] = pwmOnTime[1]; /* Second controlled signal is shifted to two times the percentage of master timer's period */
  AtomPhaseSerial_Output.pwmOnTimes[2] = pwmOnTime[2];

  IfxGtm_Atom_Timer_disableUpdate(&AtomPhaseSerial_Output.timer); /* Disable the update of master timer */
  IfxGtm_AtomSerialThreeTimersSetOnTime(&AtomPhaseSerial_Output.pwm, AtomPhaseSerial_Output.pwmOnTimes); /* Set the shadow registers of the controlled pwm signals */
  IfxGtm_Atom_Timer_applyUpdate(&AtomPhaseSerial_Output.timer);  /* Start every PWM signal at the same time */

  AtomPhaseSerial_State = ATOM_SPI_START;
}

